var view = document.createElement("view")

var sidepanel = document.createElement("sidepanel")
var main = document.createElement("main")
var mainexplore = document.createElement("main")
var mainsettings = document.createElement("main")
main.classList.add("library")
mainexplore.classList.add("explore")
mainsettings.classList.add("settings")

view.appendChild(sidepanel)
view.appendChild(main)
view.appendChild(mainexplore)
view.appendChild(mainsettings)
app.appendChild(view)